
- name:  VARIABLES
  hosts: local
  connection: local

  vars:
      COURSE: JAVA
      Name: VYSHNAVI

  tasks:
   - name: course details
      ansible.builtin.debug:
         msg: " hello {{ COURSE }} ,  baggunnava {{ Name }} "

---
# - name: VARIABLES
#   hosts: local
#   connection: local

#   vars:
#     COURSE: JAVA
#     Name: VYSHNAVI

#   tasks:
#     - name: course details
#       ansible.builtin.debug:
#         msg: "hello {{ COURSE }}, baggunnava {{ Name }}"